---
galaxy_info:
  author: ""
  license: BSD
  min_ansible_version: 1.4
  platforms:
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
      - trusty
  categories:
   - networking
   - system
dependencies: []
