---
- name: Ensure that BIND is not installed in order to avoid conflicts with dnsmasq
  apt:
    package: bind9
    state: absent
- name: Ensure that dnsmasq is not installed in order to avoid conflicts with dnsmasq
  apt:
    package: dnsmasq
    state: absent

- name: install unbound for Debian OS family
  apt: pkg=unbound state={{ unbound_pkg_state }}
  when: ansible_os_family == 'Debian' and unbound_only_zones == false
  tags: ["packages","unbound"]

- name: Ensure zones folder exist
  file: path=/etc/unbound/conf.d state=directory mode=755
  notify: restart unbound
  tags: ["configuration","unbound"]

- name: Ensure log file exist
  file: path={{unbound_logfile}} state=touch mode=755 owner=unbound
  notify: restart unbound
  tags: ["configuration","unbound"]

- name: configure add independant config file
  template:
     src={{item}}.j2
     dest="/etc/unbound/conf.d/{{item}}"
  with_items:
     - 01general.conf
     - 99forward_zone.conf
  notify: restart unbound
  when: unbound_only_zones == false
  tags: ["configuration","unbound"]

- name: configure unbound zones
  template:
     src=10zone.conf.j2
     dest="/etc/unbound/conf.d/10{{item.name}}.conf"
  with_items: "{{unbound_zones}}"
  notify: restart unbound
  tags: ["configuration","unbound"]

- name: retreive unbound conf file list
  shell: /bin/ls /etc/unbound/conf.d/
  register: unbound_conf_list
  check_mode: no
  tags: ["configuration","unbound"]

- name: configure unbound.conf to include all configuration
  template:
     src=unbound.conf.j2
     dest=/etc/unbound/unbound.conf
     validate="/usr/sbin/unbound-checkconf %s"
  notify: restart unbound
  tags: ["configuration","unbound"]

- name: Create the unbound systemd drop-in configuration directory
  file:
    path: "{{ unbound_systemd_service_path }}"
    state: directory

- name: Generate the unbound systemd drop-in service file
  template:
    src: unbound.service.j2
    dest: "{{ unbound_systemd_service_path }}/10-restart-failure.conf"
    mode: 0644

- name: Enable the unbound service
  systemd:
    daemon_reload: yes
    name: unbound.service
    enabled: yes
    state: restarted
